<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Package Information
    |--------------------------------------------------------------------------
    */
    'defaults' => [
        'vendor' => 'x-multibyte',
        'package' => 'my-package',
        'description' => 'A Laravel package Description.',
        'author' => [
            'name' => 'Roy',
            'email' => 'roy@xmultibyte.com',
        ],
        'license' => 'MIT',
        'minimum_php' => '8.2',
        'minimum_laravel' => '10.0',
    ],

    /*
    |--------------------------------------------------------------------------
    | Feature Flags
    |--------------------------------------------------------------------------
    |
    | Control which features should be generated by default
    |
    */
    'features' => [
        'facade' => true,
        'config' => true,
        'migrations' => true,
        'views' => true,
        'routes' => false,
        'middleware' => false,
        'commands' => false,
        'events' => false,
        'listeners' => false,
        'jobs' => false,
        'notifications' => false,
        'policies' => false,
        'rules' => false,
        'resources' => false,
        'tests' => true,
        'github_actions' => true,
        'readme' => true,
        'changelog' => false,
        'contributing' => false,
        'code_of_conduct' => false,
    ],

    /*
    |--------------------------------------------------------------------------
    | Directory Structure
    |--------------------------------------------------------------------------
    |
    | Customize the directory structure of generated packages
    |
    */
    'directories' => [
        'base' => 'packages',
        'structure' => [
            'config',
            'database/migrations',
            'database/factories',
            'database/seeders',
            'resources/views',
            'resources/lang',
            'routes',
            'src',
            'src/Console/Commands',
            'src/Events',
            'src/Listeners',
            'src/Jobs',
            'src/Mail',
            'src/Notifications',
            'src/Policies',
            'src/Rules',
            'src/Http/Controllers',
            'src/Http/Middleware',
            'src/Http/Requests',
            'src/Http/Resources',
            'src/Models',
            'src/Facades',
            'tests',
            'tests/Feature',
            'tests/Unit',
        ],
        'permissions' => 0755,
    ],

    /*
    |--------------------------------------------------------------------------
    | File Templates
    |--------------------------------------------------------------------------
    |
    | Configure stub file locations and mappings
    |
    */
    'stubs' => [
        'path' => 'stubs',
        'files' => [
            'composer' => 'composer.json.stub',
            'package' => 'package.stub',
            'service_provider' => 'service.provider.stub',
            'facade' => 'facade.stub',
            'config' => 'config.stub',
            'phpunit' => 'phpunit.xml.stub',
            'pest_config' => 'pest.php.stub',
            'pest_feature_test' => 'pest.feature.test.stub',
            'pest_unit_test' => 'pest.unit.test.stub',
            'test_case' => 'tests.case.stub',
            'readme' => 'readme.md.stub',
            'gitignore' => 'gitignore.stub',
            'ci' => 'ci.yml.stub',
            'changelog' => 'changelog.md.stub',
            'contributing' => 'contributing.md.stub',
            'code_of_conduct' => 'code_of_conduct.md.stub',
            'license' => 'license.stub',
            'migration' => 'migration.stub',
            'model' => 'model.stub',
            'controller' => 'controller.stub',
            'middleware' => 'middleware.stub',
            'command' => 'command.stub',
            'event' => 'event.stub',
            'listener' => 'listener.stub',
            'job' => 'job.stub',
            'notification' => 'notification.stub',
            'policy' => 'policy.stub',
            'rule' => 'rule.stub',
            'resource' => 'resource.stub',
            'request' => 'request.stub',
            'route' => 'routes.stub',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Testing Configuration
    |--------------------------------------------------------------------------
    |
    | Configure testing framework and related settings
    |
    */
    'testing' => [
        'framework' => 'pest', // phpunit, pest
        'create_feature_tests' => true,
        'create_unit_tests' => true,
        'parallel_testing' => false,
        'coverage' => [
            'enabled' => true,
            'format' => 'html', // html, clover, xml
            'directory' => 'coverage',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Git Configuration
    |--------------------------------------------------------------------------
    |
    | Configure Git-related file generation
    |
    */
    'git' => [
        'gitignore' => true,
        'github_actions' => true,
        'workflows' => [
            'ci' => true,
            'release' => false,
            'security' => false,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Composer Configuration
    |--------------------------------------------------------------------------
    |
    | Customize composer.json generation
    |
    */
    'composer' => [
        'type' => 'library',
        'keywords' => ['laravel', 'package'],
        'homepage' => null,
        'support' => [
            'issues' => null,
            'source' => null,
            'docs' => null,
        ],
        'require_dev' => [
            'orchestra/testbench' => '^8.0|^9.0',
            'pestphp/pest' => '^2.0',
            'pestphp/pest-plugin-laravel' => '^2.0',
            'laravel/pint' => '^1.0',
        ],
        'scripts' => [
            'test' => 'vendor/bin/pest',
            'test-coverage' => 'vendor/bin/pest --coverage',
            'format' => 'vendor/bin/pint',
        ],
        'extra' => [
            'laravel' => [
                'providers' => [],
                'aliases' => [],
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Naming Conventions
    |--------------------------------------------------------------------------
    |
    | Configure naming conventions for generated files and classes
    |
    */
    'naming' => [
        'namespace_separator' => '\\',
        'class_suffix' => [
            'service_provider' => 'ServiceProvider',
            'facade' => '',
            'controller' => 'Controller',
            'middleware' => 'Middleware',
            'command' => 'Command',
            'event' => 'Event',
            'listener' => 'Listener',
            'job' => 'Job',
            'notification' => 'Notification',
            'policy' => 'Policy',
            'rule' => 'Rule',
            'resource' => 'Resource',
            'request' => 'Request',
        ],
        'file_naming' => 'StudlyCase', // StudlyCase, snake_case, kebab-case
    ],

    /*
    |--------------------------------------------------------------------------
    | Validation Rules
    |--------------------------------------------------------------------------
    |
    | Configure validation rules for package generation
    |
    */
    'validation' => [
        'vendor_pattern' => '/^[a-z0-9-]+$/',
        'package_pattern' => '/^[a-z0-9-]+$/',
        'reserved_names' => [
            'laravel', 'illuminate', 'symfony', 'composer', 'vendor',
            'app', 'config', 'database', 'public', 'resources', 'routes',
            'storage', 'tests', 'bootstrap', 'artisan',
        ],
        'max_name_length' => 50,
        'min_name_length' => 2,
    ],

    /*
    |--------------------------------------------------------------------------
    | Output Configuration
    |--------------------------------------------------------------------------
    |
    | Configure command output and logging
    |
    */
    'output' => [
        'verbose' => false,
        'show_progress' => true,
        'log_generation' => false,
        'log_file' => 'storage/logs/package-generator.log',
    ],
];
