name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2', '8.3' ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      - name: Validate composer.json
        run: composer validate --strict || echo "composer.json validation warning (non-blocking)"

      - name: Check code formatting with Pint (non-blocking)
        run: |
          composer format --dry-run
        continue-on-error: true

      - name: Run static analysis with PHPStan (non-blocking)
        run: composer analyse
        continue-on-error: true

      - name: Run tests with Pest
        run: composer test
