name: Clean Failed Workflow Runs

on:
  schedule:
    # 每 12 小时执行一次（UTC 时间 00:00 和 12:00）
    - cron: '0 */12 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  clean:
    name: Delete failed workflow runs
    runs-on: ubuntu-latest
    permissions:
      actions: write  # 必须授权才能删除 workflow runs

    steps:
      - name: Delete failed workflow runs
        run: |
          # 使用 GitHub API 分页获取所有失败的 runs 并删除
          gh api \
            --paginate \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/actions/runs" \
            --jq '.workflow_runs[] | select(.conclusion == "failure") | .id' \
          | while read run_id; do
              if [ -n "$run_id" ]; then
                echo "Deleting failed run: $run_id"
                gh api \
                  --method DELETE \
                  "/repos/${{ github.repository }}/actions/runs/$run_id"
              fi
            done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
